- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include: tasks/ssh.yaml
    - include: tasks/brew.yaml
    - include: tasks/zsh.yaml
    - include: tasks/dotfiles.yaml
