- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dotfiles: "{{ lookup('env', 'HOME') }}/.dotfiles"
    sdkman: "source {{ lookup('env', 'HOME') }}/.sdkman/bin/sdkman-init.sh"
  tasks:
    - include: tasks/ssh.yaml
    - include: tasks/brew.yaml
    - include: tasks/zsh.yaml
    - include: tasks/skds.yaml
    - include: tasks/dotfiles.yaml
