- name: Check if sdkman is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.sdkman"
  register: sdk

- name: Installing sdk manager
  shell: curl -s "https://get.sdkman.io" | bash
  when: not sdk.stat.exists

- name: Update sdkman
  shell: "{{ sdkman }} && sdk selfupdate"
  when: sdk.stat.exists

- name: Install sdks
  shell: "{{ sdkman }} && sdk install {{ item }}"
  with_items:
    - java
  when: not sdk.stat.exists