# ZSH is installed by default on Mac since macOS Catalina

- name: Check if we have a zsh configuration already
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_stats
  tags:
  - shell

- name: Install Oh-My-Zsh
  ansible.builtin.shell:
    cmd: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh -s -- -y
  tags:
  - shell
  when: oh_my_stats.stat.exists == False
  become_user: giograno

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  when: oh_my_stats.stat.exists == False
  tags:
  - shell

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  when: oh_my_stats.stat.exists == False
  tags:
  - shell